### ISSUE TITLE
BCH QR code amount precision too high

### ISSUE THREAD

**Issue by Rucknium** [plowsof/flipstarter-waas-wip#7]
The QR code for BCH gives 12 decimal places. BCH only has a maximum of 8. This issue may also affect BTC.

**Comment by plowsof** [comment]
Thank you for reporting the issue, my apologies, i did not consider this at all. 
fixed [here](https://github.com/plowsof/flipstarter-waas-wip/commit/32cd2628a4285437eaf698e8ee52b77e948e79ef)
